# Generated by Django 2.2 on 2019-07-23 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerName', models.CharField(max_length=150)),
                ('Amount', models.FloatField()),
                ('dateCreted', models.DateField(blank=True, default=datetime.datetime.now)),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='NegashaWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('Amount', models.FloatField()),
                ('dateCreted', models.DateField(blank=True, default=datetime.datetime.now)),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('Amount', models.FloatField()),
                ('dateCreted', models.DateField(blank=True, default=datetime.datetime.now)),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='CebakaWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='BulatWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='BayatWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('flour', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('projectId', models.ForeignKey(on_delete=None, to='MusaApp.Project')),
            ],
        ),
    ]
